#############################
###   shared settings     ###
#############################
x-shared-settings: &shared-settings
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s
  
  environment:
    - DISPLAY=${DISPLAY}
    - COMMAND=${COMMAND}
  devices:
    - /dev:/dev
    

#############################
###   Container Startup   ###
#############################
services:
  koch-actpp:
    <<: *shared-settings
    build: 
      context: .  
      dockerfile: Dockerfile
    image: pomelo925/hrc-koch:gpu
    container_name: actpp-gpu

    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - $HOME/.Xauthority:/root/.Xauthority
      - /dev/shm:/dev/shm
    
    command: "/bin/bash -c \"${COMMAND}\""