name: act-plus-plus cpu image

on:
  push:
    branches: [ main ]
    paths:
      - docker/gpu/Dockerfile
      - .github/workflows/gpu.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Repo Checkout 
      uses: actions/checkout@v3
    - 
      name: Docker meta
      id: meta
      # Ref: https://github.com/docker/metadata-action
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/hrc-koch-actpp
        tags: gpu
    - 
      name: Docker Hub Log-in
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    # Build Docker image
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: docker/gpu
        load: true # Load the image into Docker environment
        tags: ${{ steps.meta.outputs.tags }}
        push: false

    # Push Docker image to registry
    - name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: docker/gpu
        push: true
        tags: ${{ steps.meta.outputs.tags }}